#common
logging.level.telran=trace
app.range.provider.path=/sensor/range
app.emails.provider.path=/sensor/emails

#MongoDB
spring.data.mongodb.uri=mongodb+srv://root:12345.com@javatest.fhuis.mongodb.net/probes?retryWrites=true&w=majority&appName=JavaTest 
#Cloud Confluence Kafka
# Required connection configs for Kafka producer, consumer, and admin
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.bootstrap-servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='XKJ7PP2EKETBZQ2M' password="${STREAM_API_PASSWORD}";
spring.kafka.properties.security.protocol=SASL_SSL
# Best practice for higher availability in Apache Kafka clients prior to 3.0
spring.kafka.properties.session.timeout.ms=45000
client.id=ccloud-springboot-client-a58ca601-47fd-422c-88fc-23f6e08266b5

#sensor-data configuration
app.sensors.producer.binding.name=probesSupplier-out-0
app.analyzer.consumer.binding.name=analyzerConsumer-in-0
app.avg.reducer.producer.binding.name=avgReducerConsumer-in-0
spring.cloud.stream.bindings.analyzerConsumer-in-0.destination=sensor-data
spring.cloud.stream.bindings.analyzerConsumer-in-0.group=analyzer-group
spring.cloud.stream.bindings.avgReducerConsumer-in-0.destination=sensor-data
spring.cloud.stream.bindings.avgReducerConsumer-in-0.group=avg-reducer-group
spring.cloud.stream.bindings.avgReducerConsumer-in-0.destination=sensor-data
#deviation configuration
app.analyzer.producer.binding.name=deviation-out-0
spring.cloud.stream.bindings.deviation-out-0.destination=deviation
spring.cloud.stream.bindings.emailNotifierConsumer-in-0.destination=deviation
spring.cloud.stream.bindings.emailNotifierConsumer-in-0.group=email-notifier-group
#avg-values configuration
app.avg.reducer.producer.binding.name=avg-values-out-0
spring.cloud.stream.bindings.avg-values-out-0.destination=avg-values
spring.cloud.stream.bindings.avgPopulatorConsumer-in-0.destination=avg-values
spring.cloud.stream.bindings.avgPopulatorConsumer-in-0.group=avg-populator-consumer-group
#update-data configuration
app.update.data.binding.name=updateData-out-0
spring.cloud.stream.bindings.updateData-out-0.destination=update-data
spring.cloud.stream.bindings.updateRangeConsumer-in-0.destination=update-data
spring.cloud.stream.bindings.updateEmailsConsumer-in-0.destination=update-data

